### ISSUE TITLE
Flasher Utility Procedure

### ISSUE THREAD

**Issue by jhosee** [minershive/hive-flasher#2]
Hello, when I boot off the flasher img, I don't receive the same output as displayed in the screenshot where it dd writes to the ssd.  It seems that it just goes straight to headless mode.  Is there a way to manually complete the operation upon boot completion from USB?  Thank you for any guidance.

**Comment by minershive** [comment]
headless? there should be some image. try to change VGA output. 
here is how it looks like https://www.youtube.com/watch?v=J7VpPt0RE6M
