### ISSUE TITLE
Flashing does not work

### ISSUE THREAD

**Issue by mooleshacat** [minershive/hive-flasher#4]
Hi can you just please post an ISO?

The flash has failed 10 different times and each time is no different. I even tried flashing it on Linux. I am at my wits end. I am trying Rufus but that is my last idea.

When it fails it never gives a reason so I have to guess why. Also it does not boot either but this could be due to the failure.

Thanks

**Comment by mooleshacat** [comment]
I even got this time it to verify properly and it gave green checkmark but when I put in miner and boot it does not recognize the USB as bootable...

I even re-downloaded every file. Please convert to an iso with interactive installer to set up the miner so can be burned with any image burner without problems.

Thanks

**Comment by mooleshacat** [comment]
I figured it out. I googled for it and found a link which the page was deleted on your website but I viewed it with cache and it said to set legacy mode on USB in the BIOS.

I turned it on, and it works now. Thanks :) +1

**Comment by lrossy** [comment]
I have the same problem, USB is not bootable. BIOS shows Legacy USB support is Enabled, any ideas what else could be causing this?

**Comment by mooleshacat** [comment]
I also tried Rufus maybe it works better?

I swear there must be a way to make it bootable. Once I get it working again I am labelling the USB stick and not overwriting it lol
